import Head from "next/head";
import Footer from "../components/client/Footer";
import Header from "../components/client/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="h-[5000px]">
        <h1>Hello World</h1>
      </div>
      <Footer />
    </div>
  );
}
