import Head from "next/head";
import React, { useState } from "react";
import "react-multi-carousel/lib/styles.css";
import "swiper/css";
import "swiper/css/pagination";
import ListProductComponent from "../components/client/ListProductComponent";
import Pagination from "../components/client/Pagination";
import Slider from "../components/client/Slider";
import { BannerCarousel } from "../components/client/BannerCarousel";
import MainLayout from "../components/layout/main";
import axios from "axios";
import { useDispatch, useSelector } from "react-redux";
import { getListProduct } from "../redux/admin/productSlice";

export default function Home(props) {

  const [totalProduct, setTotalProduct] = useState(props.count);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BannerCarousel />
      <Slider arrProduct={props.listProduct.slice(0, 8)} />
      <ListProductComponent arrProduct={props.listProduct} />
      <Pagination totalProduct={totalProduct} />
    </>
  );
}

export async function getServerSideProps() {
  const res = await axios.get(
    "https://63030a4dc6dda4f287c1d8d4.mockapi.io/product?page=1&limit=10"
  );
  const data = res.data;
  console.log("List product", data.products);

  return {
    props: {
      listProduct: data.products,
      count: data.count,
    },
  };
}

Home.Layout = MainLayout;
